  version: '3.8'

  services:
    mysql_db:
      image: mysql:8.0
      container_name: super_win_mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: super_win_db
        MYSQL_ROOT_PASSWORD: Superwin@Root
        MYSQL_PASSWORD: Superwin@9988
        MYSQL_USER: admin
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      ports:
        - "3307:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      networks:
        - super_win_network

    laravel_app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: super_win_app
      restart: unless-stopped
      working_dir: /var/www
      volumes:
        - ./:/var/www
        - ./storage:/var/www/storage
        - ./bootstrap/cache:/var/www/bootstrap/cache
      ports:
        - "8000:8000"
      depends_on:
        - mysql_db
      networks:
        - super_win_network
      command: php artisan serve --host=0.0.0.0 --port=8000

  volumes:
    mysql_data:
      driver: local

  networks:
    super_win_network:
      driver: bridge